### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_default_verify_paths'

### ISSUE THREAD

**Issue by patnaik-g** [corpnewt/GenSMBIOS#17]
Running on MacOS 10.14.6 (Mojave) with python 2.7.5
Traceback (most recent call last):
  File "./GenSMBIOS.command", line 439, in <module>
    s = Smbios()
  File "./GenSMBIOS.command", line 14, in __init__
    self.d = downloader.Downloader()
  File "/Volumes/Users/Users/patnaik/Desktop/Hackintosh/Big Sur/GenSMBIOS-master/Scripts/downloader.py", line 18, in __init__
    cafile = ssl.get_default_verify_paths().openssl_cafile
AttributeError: 'module' object has no attribute 'get_default_verify_paths'

This happens with many of your utilities that I tried.

**Comment by lebeier** [comment]
use python3 instead of python2.

```
python3 GenSMBIOS.command
```
